from pathlib import Path

# Single source of truth for the version: the VERSION file (bumped by repo-release).
VERSION = (Path(__file__).resolve().parent / "VERSION").read_text().strip()
ITERATION_INTERVALS = {
    "week": {"weeks": 1},
    "2 weeks": {"weeks": 2},
    "month": {"weeks": 4}
}
DEFAULT_ITERATION_SLOT = {"weekday": 5, "hour": 11, "minute": 0}
MOTIVATIONAL_QUOTES = [
    "Push yourself, because no one else is going to do it for you.",
    "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
    "Dream it. Believe it. Build it.",
    "Don't stop until you're proud.",
    "Your limitation—it's only your imagination.",
    "Do something today that your future self will thank you for.",
    "The way to get started is to quit talking and begin doing.",
    "You miss 100% of the shots you don't take.",
    "Discipline is choosing between what you want now and what you want most.",
    "Small steps every day.",
    "Done is better than perfect.",
    "Action is the foundational key to all success.",
    "Hard choices, easy life. Easy choices, hard life.",
    "If it is important to you, you will find a way. If not, you'll find an excuse.",
    "Motivation gets you going, habit keeps you going.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Slow progress is still progress.",
    "Don't count the days, make the days count.",
    "You don't have to be great to start, but you have to start to be great.",
    "The only impossible journey is the one you never begin.",
    "Act as if what you do makes a difference. It does.",
    "Success is the sum of small efforts repeated day in and day out.",
    "Energy and persistence conquer all things.",
    "Courage doesn't always roar. Sometimes it whispers: 'I'll try again tomorrow.'",
    "Don't wait. The time will never be just right.",
    "A year from now you will wish you had started today.",
    "Fall seven times, stand up eight.",
    "The secret to getting ahead is getting started.",
    "What you do today can improve all your tomorrows.",
    "Great things never come from comfort zones.",
    "Dream bigger. Do bigger.",
    "The expert in anything was once a beginner.",
    "Focus on being productive instead of busy.",
    "Opportunities don't happen. You create them.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success doesn't just find you. You have to go out and get it.",
    "Don't stop when you're tired. Stop when you're done.",
    "The only way to do great work is to love what you do.",
    "Consistency is more important than perfection.",
    "You are what you do, not what you say you'll do.",
    "Rise up and attack the day with enthusiasm.",
    "One small positive thought in the morning can change your whole day.",
    "Trust the process.",
    "Progress, not perfection.",
    "If you're tired of starting over, stop giving up.",
    "Be stronger than your excuses.",
    "Make it happen. Shock everyone.",
    "Life begins at the end of your comfort zone.",
    "You're one decision away from a totally different life.",
    "The difference between who you are and who you want to be is what you do.",
    "Winners focus on winning. Losers focus on winners.",
    "Nothing will work unless you do.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Discipline is the bridge between goals and accomplishment.",
    "Quality is not an act, it is a habit.",
    "The secret of your future is hidden in your daily routine.",
    "Stop waiting for Friday, for summer, for someone to fall in love with you. Life happens in the moment you're in.",
    "Show up. Show up. Show up. And after a while the muse shows up too.",
    "A goal without a plan is just a wish.",
    "Begin anywhere.",
    "Starve your distractions, feed your focus.",
    "Bananas don't grow on procrastination trees.",
    "Mindbaboon is watching.",
    "Stop scrolling, start doing."
]
