version: '3.8'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - mindbaboon_data:/app/data
    environment:
      - FLASK_APP=mindbaboon.py
      - FLASK_ENV=developments
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - EMAIL_SMTP_SERVER=smtp.gmail.com
      - EMAIL_SMTP_PORT=587
      - EMAIL_USERNAME=you@example.com
      - EMAIL_PASSWORD=***REMOVED***
      - DEFAULT_TO_ADDRESS=you@example.com
      - TZ=Europe/Prague

volumes:
  mindbaboon_data: