version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - FLASK_APP=mindbaboon.py
      - FLASK_ENV=production
      - EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      - EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      - EMAIL_USERNAME: ${EMAIL_USERNAME}
      - EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      - DEFAULT_TO_ADDRESS: ${DEFAULT_TO_ADDRESS}
    restart: unless-stopped